# Generated by Django 6.0.3 on 2026-04-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationlog',
            name='sender',
            field=models.CharField(choices=[('AI', 'AI'), ('USER', 'User')], max_length=10),
        ),
    ]
