# Generated by Django 6.0.3 on 2026-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_conversationlog_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationlog',
            name='stage',
            field=models.CharField(choices=[('START', 'Start'), ('REMINDER', 'Reminder'), ('NEGOTIATION', 'Negotiation'), ('CLOSURE', 'Closure')], default='START', max_length=20),
        ),
    ]
